//
//  InformationModels.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CountryDetails {
    // MARK: Use cases
    
    enum ShowCountryDetails {
        struct Request { }
        
        struct Response {
            let country: Country
        }
        
        struct ViewModel {
            let capital: String
        }
    }
    
    enum ShowCountryWeather {
        struct Request { }
        
        struct Response {
            let weather: Weather
        }
        
        struct ViewModel {
            let temp: String
            let humidity: String
        }
    }
    
    enum GetWeather {
        
        struct Request {  }
        
        struct Response { let data: Weather }
        
        struct ViewModel { let temp: String; let humidity: String }
    }
}
