//
//  InformationRouter.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InformationRoutingLogic { }

protocol InformationDataPassing {
    var dataStore: InformationDataStore { get }
}

final class InformationRouter: InformationRoutingLogic, InformationDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: InformationViewController?
    private(set) var dataStore: InformationDataStore
    
    // MARK: - Object Lifecycle
    
    init(dataStore: InformationDataStore) {
        self.dataStore = dataStore
    }
}

