//
//  InformationWorker.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InformationWorkerLogic {
    func fetchWeather() async throws -> Weather
}

final class InformationWorker: InformationWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    private var urlString = ""
    
    init(apiManager: APIManager, lat: Double, lon: Double) {
        self.api = apiManager
        self.urlString = "https://api.openweathermap.org/data/2.5/weather?lat=\(lat)&lon=\(lon)&appid=2d669ed45701a062b61b56842e174fa8"
    }
    
    // MARK: - Methods
    
    func fetchWeather() async throws -> Weather {
        try await api.fetchData(urlString: urlString, decodingType: Weather.self)
    }
}

