//
//  TablePresenter.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TablePresentationLogic
{
    func presentCountries(response: Table.GetCountries.Response)
    func presentSelectedCountry(response: Table.ShowCountryDetails.Response)
}

class TablePresenter: TablePresentationLogic
{
    // MARK: - Clean Components
    
    weak var viewController: TableDisplayLogic?
    
    // MARK: - Methods
    
    private func configureTableModel(from data: [Country]) -> [AbstractModel] {
        var tableModel = [AbstractModel]()
        
        tableModel.append(contentsOf: data.map { CountryCellModel(title: $0.name ?? "no name provided", capital: $0.capital ?? "no capital provided", latlng: $0.latlng) })
        
        return tableModel
    }
    
}

// MARK: - CountriesPresentationLogic

extension TablePresenter {
    func presentSelectedCountry(response: Table.ShowCountryDetails.Response) {
        viewController?.displaySelectedCountry(viewModel: Table.ShowCountryDetails.ViewModel())
    }
    
    func presentCountries(response: Table.GetCountries.Response) {
        let viewModel = configureTableModel(from: response.data)
        viewController?.displayCountries(viewModel: Table.GetCountries.ViewModel(tableData: viewModel))
    }
}
