//
//  TableModels.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Table
{
    // MARK: Use cases
    
    enum GetCountries {
        
        struct Request {  }
        
        struct Response { let data: [Country] }
        
        struct ViewModel { let tableData: [AbstractModel] }
    }
    
    enum ShowCountryDetails {
        
        struct Request { let coord: [Double] }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
}
