//
//  TableWorker.swift
//  28.Davit.Shavtvalishvili
//
//  Created by a on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TableWorkerLogic {
    func fetchCountries() async throws -> [Country]
}

final class TableWorker: TableWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    private let urlString = "https://restcountries.com/v2/all"
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func fetchCountries() async throws -> [Country] {
        try await api.fetchData(urlString: urlString, decodingType: [Country].self)
    }
}
